const fs = require("fs");
const path = require("path");

const apiBase = (process.env.API_BASE_URL || "").replace(/\/$/, "");
const content = `// Auto-generated by scripts/generate-config.js
window.__CONFIG__ = { API_BASE_URL: ${JSON.stringify(apiBase)} };
`;

fs.writeFileSync(path.join(__dirname, "..", "config.js"), content, "utf8");
console.log(`[config] API_BASE_URL=${apiBase || "(empty)"}`);
